---

- name: update apt
  command: apt-get update

- name: install nginx
  action: apt name=nginx

- name: delete default in sites-available
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: copy mediacenter to sites-available
  template: src=mediacenter dest=/etc/nginx/sites-available/mediacenter mode=0644

- name: copy mediacenter-cache to conf.d
  template: src=mediacenter-cache dest=/etc/nginx/conf.d/mediacenter-cache mode=0644

- name: link mediacenter in sites-enabled
  file: src=/etc/nginx/sites-available/mediacenter dest=/etc/nginx/sites-enabled/mediacenter state=link
  notify:
    - restart nginx




