---
- name: update apt
  command: apt-get update

- name: install openssl
  action: apt name=openssl

- name: create ssl directory in nginx
  file: path=/etc/nginx/ssl state=directory


- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C={{ssl_country}}/ST={{ssl_state}}/L={{ssl_locality}}/O={{ssl_organization}}/CN={{nginx_domain}}" -days 3650 -keyout /etc/nginx/ssl/mediacenter.key -out /etc/nginx/ssl/mediacenter.crt -extensions v3_ca creates=/etc/nginx/ssl/mediacenter.crt
  notify:
    - restart nginx
