---
- name: install PM2 npm module
  npm: name=pm2 global=yes

- name: perform the couchdb admin related tasks
  shell: /etc/ContentDiscovery/couchdb_tasks.sh

- name: restart couchdb
  service: name=couchdb state=restarted
