---
- name: stop the ContentDiscovery node server
  shell: pm2 stop {{ContentDiscoveryWebServerName}}
  ignore_errors: yes

- name: delete the ContentDiscovery node server from the service list
  shell: pm2 delete {{ContentDiscoveryWebServerName}}
  ignore_errors: yes

- name: delete the old project directory
  shell: rm -rf {{project_directory}}

- name: create the project directory if it's not available
  file: path={{project_directory}} state=directory mode=0744 recurse=yes

- name: copy the dist.tar.gz to the project directory
  shell: cp "/var/lib/go-agent/pipelines/{{pipeline_deployment_folder_name}}/trunk/{{artifact}}" {{project_directory}}

- name: untar the project directory
  shell: tar -xvzf "{{project_directory}}/{{artifact}}" --directory {{project_directory}}

- name: copy the server application json file
  shell: cp "{{ConfigFilesPath}}/server_application.json" "{{project_directory}}/dist/server/config/application.json"

- name: copy the server client parameters file
  shell: cp "{{ConfigFilesPath}}/server_clientParameters.json" "{{project_directory}}/dist/server/config/clientParameters.json"

- name: copy the client config file
  shell: cp "{{ConfigFilesPath}}/client_config.js" "{{project_directory}}/dist/client/config/config.js"

- name: add read,write and execute permissions to project folder
  shell: chmod -R u+rwx {{project_directory}}

- name: migrate all the dbs
  shell: NODE_ENV="{{project_environment}}" node {{project_directory}}/dist/server/src/migration.js

- name: create the server options json file.
  template: src=start-server dest="{{project_directory}}/run_pm_options.json" mode=0644

- name: start the application server
  shell: pm2 start {{project_directory}}/run_pm_options.json