---
- name: stop the ContentDiscovery node server
  shell: pm2 stop {{ContentDiscoveryWebServerName}}
  ignore_errors: yes

- name: delete the ContentDiscovery node server from the service list
  shell: pm2 delete {{ContentDiscoveryWebServerName}}
  ignore_errors: yes

- name: delete the old project directory
  shell: rm -rf {{project_directory}}

- name: create the project directory if it's not available
  file: path={{project_directory}} state=directory group={{groupname}} owner={{owner}} mode=0744 recurse=yes

- name: copy the dist.tar.gz to the project directory
  shell: cp "{{package_source_path}}/{{artifact}}" {{project_directory}}

- name: untar the project directory
  shell: tar -xvzf "{{project_directory}}/{{artifact}}" --directory {{project_directory}}

- name: migrate all the dbs
  shell: node {{project_directory}}/dist/server/src/migration.js --admin_user_name='admin' --admin_password='M@d!ac3nt53'

- name: create the server options json file.
  shell: echo "{{ lookup('file', './files/{{environment}}.json') }}" > {{project_directory}}/run_pm_options.json

- name: start the application server
  shell: pm2 start {{project_directory}}/run_pm_options.json
