- hosts: web
  sudo: True
  vars:
    - go_server_ip: 46.101.245.151
  roles:
    - PreInstallationTasks
    - Ansibles.build-essential
    - ANXS.build-essential
    - Ansibles.erlang
    - guillaumededrie.couchdb
    - gotansible.nodejs
    - PostInstallationTasks
    - goagent
    - nginx
