---
- name: clear go agent apt get source list
  shell: echo "deb https://download.gocd.io /" > /etc/apt/sources.list.d/gocd.list

- name: download go agent to apt-get repository
  shell: curl https://download.gocd.io/GOCD-GPG-KEY.asc | sudo apt-key add -

- name: do apt-get update
  shell: apt-get update

- name: install go agent
  shell: apt-get install go-agent

- name: map the go agent with the go server
  shell: sed -i -e 's/GO_SERVER_URL=https:\/\/127.0.0.1:8154\/go/GO_SERVER_URL={{go_server}}/g' /etc/default/go-agent

- name: restart the go agent
  service: name=go-agent state=restarted

